"""updated workout plan model and user profile model

Revision ID: 10cdbba0c512
Revises: df444e225f28
Create Date: 2025-03-02 15:43:59.265206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cdbba0c512'
down_revision: Union[str, None] = 'df444e225f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('gender', sa.String(), nullable=True))
    op.execute("UPDATE user_profile SET gender = 'Not Specified' WHERE gender IS NULL")
    op.alter_column('user_profile', 'gender', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'gender')
    # ### end Alembic commands ###
