"""added workoutplan week and days  model

Revision ID: 39e8df8de138
Revises: 5d57d6c86cec
Create Date: 2025-02-23 18:02:58.333373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e8df8de138'
down_revision: Union[str, None] = '5d57d6c86cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plan_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plan_weeks_id'), 'workout_plan_weeks', ['id'], unique=False)
    op.create_table('workout_plan_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_week_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workout_plan_week_id'], ['workout_plan_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plan_days_id'), 'workout_plan_days', ['id'], unique=False)
    op.add_column('workout_plan_exercises', sa.Column('workout_plan_day_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workout_plan_exercises', 'workout_plan_days', ['workout_plan_day_id'], ['id'], ondelete='CASCADE')
    op.add_column('workout_plans', sa.Column('weeks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plans', 'weeks')
    op.drop_constraint(None, 'workout_plan_exercises', type_='foreignkey')
    op.drop_column('workout_plan_exercises', 'workout_plan_day_id')
    op.drop_index(op.f('ix_workout_plan_days_id'), table_name='workout_plan_days')
    op.drop_table('workout_plan_days')
    op.drop_index(op.f('ix_workout_plan_weeks_id'), table_name='workout_plan_weeks')
    op.drop_table('workout_plan_weeks')
    # ### end Alembic commands ###
