"""added workout logs exercies

Revision ID: b8b64e2e18b2
Revises: a881f1f64451
Create Date: 2025-02-02 17:12:09.030693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b64e2e18b2'
down_revision: Union[str, None] = 'a881f1f64451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_log_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_log_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets_completed', sa.Integer(), nullable=True),
    sa.Column('reps_completed', sa.Integer(), nullable=True),
    sa.Column('weight_used', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_log_exercises_id'), 'workout_log_exercises', ['id'], unique=False)
    op.add_column('workout_logs', sa.Column('status', sa.String(), server_default='completed', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'status')
    op.drop_index(op.f('ix_workout_log_exercises_id'), table_name='workout_log_exercises')
    op.drop_table('workout_log_exercises')
    # ### end Alembic commands ###
