"""added country code column to profile table

Revision ID: 7b8eec84d0a3
Revises: d0c0884dc4f9
Create Date: 2025-07-24 17:23:36.963743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8eec84d0a3'
down_revision: Union[str, None] = 'd0c0884dc4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_progress_user_id', table_name='progress')
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=True)
    op.add_column('user_profile', sa.Column('country_code', sa.String(), nullable=False))
    op.drop_index('ix_user_profile_contact_number', table_name='user_profile')
    op.create_unique_constraint(None, 'user_profile', ['contact_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_workout_plans_user_id_to_auth_users', 'workout_plans', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.create_index('ix_workout_plans_user_id', 'workout_plans', ['user_id'], unique=False)
    op.create_foreign_key('fk_workout_logs_user_id_to_auth_users', 'workout_logs', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.create_index('ix_workout_logs_user_id', 'workout_logs', ['user_id'], unique=False)
    op.create_foreign_key('fk_user_profile_user_id_to_auth_users', 'user_profile', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_index('ix_user_profile_contact_number', 'user_profile', ['contact_number'], unique=True)
    op.drop_column('user_profile', 'country_code')
    op.create_foreign_key('fk_progress_user_id_to_auth_users', 'progress', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.create_index('ix_progress_user_id', 'progress', ['user_id'], unique=False)
    # ### end Alembic commands ###
