"""removed unique constraint

Revision ID: 9fea74d0fae5
Revises: 7b8eec84d0a3
Create Date: 2025-08-05 11:23:37.967838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fea74d0fae5'
down_revision: Union[str, None] = '7b8eec84d0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_progress_user_id', table_name='progress')
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.create_index('ix_progress_user_id', 'progress', ['user_id'], unique=True)
    # ### end Alembic commands ###
