"""empty message

Revision ID: db12c0d13f2a
Revises: 33dc174b26d1
Create Date: 2025-07-24 16:40:23.411296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db12c0d13f2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # These commands handle the user_id FKs you intentionally removed in your models
    op.drop_constraint('fk_progress_user_id', 'progress', type_='foreignkey')
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_user_profile_user_id', 'user_profile', type_='foreignkey')
    op.drop_constraint('fk_workout_logs_user_id', 'workout_logs', type_='foreignkey')
    op.drop_constraint('fk_workout_plans_user_id', 'workout_plans', type_='foreignkey')

    # Drop the old constraints from workout_log_exercises
    op.drop_constraint('workout_log_exercises_workout_log_id_fkey', 'workout_log_exercises', type_='foreignkey')
    op.drop_constraint('workout_log_exercises_exercise_id_fkey', 'workout_log_exercises', type_='foreignkey')
    
    # Re-create the constraints with ON DELETE CASCADE
    op.create_foreign_key(
        'fk_workout_log_exercises_workout_log_id', # New constraint name
        'workout_log_exercises', 'workout_logs',
        ['workout_log_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_workout_log_exercises_exercise_id', # New constraint name
        'workout_log_exercises', 'exercise',
        ['exercise_id'], ['exercise_id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new constraints with ON DELETE CASCADE
    op.drop_constraint('fk_workout_log_exercises_workout_log_id', 'workout_log_exercises', type_='foreignkey')
    op.drop_constraint('fk_workout_log_exercises_exercise_id', 'workout_log_exercises', type_='foreignkey')

    # Re-create the foreign keys that you are removing in your models
    op.create_foreign_key('fk_workout_plans_user_id', 'workout_plans', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key('fk_workout_logs_user_id', 'workout_logs', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key('fk_user_profile_user_id', 'user_profile', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_progress_user_id', 'progress', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    
    # Re-create the old constraints without ON DELETE CASCADE
    op.create_foreign_key('workout_log_exercises_workout_log_id_fkey', 'workout_log_exercises', 'workout_logs', ['workout_log_id'], ['id'])
    op.create_foreign_key('workout_log_exercises_exercise_id_fkey', 'workout_log_exercises', 'exercise', ['exercise_id'], ['exercise_id'])
    # ### end Alembic commands ###